# CMake generated Testfile for 
# Source directory: D:/developpements/visual/StochasticDithering/delaunator-cpp/test
# Build directory: D:/developpements/visual/StochasticDithering/delaunator-cpp/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(issue-8 "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/issue-8")
  set_tests_properties(issue-8 PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;25;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(issue-8 "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/issue-8")
  set_tests_properties(issue-8 PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;25;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(issue-8 "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/issue-8")
  set_tests_properties(issue-8 PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;25;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(issue-8 "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/issue-8")
  set_tests_properties(issue-8 PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;25;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
else()
  add_test(issue-8 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(delaunator.test "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/delaunator.test")
  set_tests_properties(delaunator.test PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;26;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(delaunator.test "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/delaunator.test")
  set_tests_properties(delaunator.test PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;26;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(delaunator.test "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/delaunator.test")
  set_tests_properties(delaunator.test PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;26;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(delaunator.test "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/delaunator.test")
  set_tests_properties(delaunator.test PROPERTIES  WORKING_DIRECTORY "D:/developpements/visual/StochasticDithering/delaunator-cpp/bin/.." _BACKTRACE_TRIPLES "D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;16;add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;26;d_add_test;D:/developpements/visual/StochasticDithering/delaunator-cpp/test/CMakeLists.txt;0;")
else()
  add_test(delaunator.test NOT_AVAILABLE)
endif()
